FROM bellsoft/liberica-openjdk-alpine:11

ARG BOT_TOKEN_ARG
ENV BOT_TOKEN=$BOT_TOKEN_ARG

ARG DB_USERNAME_ARG
ENV DB_USERNAME=$DB_USERNAME_ARG

ARG DB_PASSWORD_ARG
ENV DB_PASSWORD=$DB_PASSWORD_ARG

ARG DB_HOST_IP_ARG
ENV DB_HOST_IP=$DB_HOST_IP_ARG

ARG DB_PORT_ARG
ENV DB_PORT=$DB_PORT_ARG

ARG DB_DATABASE_NAME_ARG
ENV DB_DATABASE_NAME=$DB_DATABASE_NAME_ARG

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app.jar"]